# Generated by Django 3.1.2 on 2020-10-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201013_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
