# Generated by Django 3.1.2 on 2020-10-20 10:36

from django.db import migrations, models
import main_app.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201020_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='public_id',
            field=models.IntegerField(default=main_app.utils.id_generator, unique=True),
        ),
    ]
