# Generated by Django 3.1.2 on 2020-10-20 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_apartment_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='number',
        ),
    ]
