# Generated by Django 3.1.2 on 2020-10-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_floor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='hash',
            field=models.UUIDField(blank=True, default=None, unique=True),
        ),
    ]
